Logica de negocio para administracion
mundobaton/apd-tpo pull request #3
Opened 2018-05-19 20:22 UTC by ffels

Cuando cree el branch me confundi con el nombre.
Hice el SistemaDeposito() y los metodos que vi en el diagrama de clases y secuencia.
Agrege un par de daos y metodos a clases.

2018-05-19 22:28 UTC, erikannunez requested changes
Hay que cambiar la branch base a develop, corregir los cambios y crear nuevamente el PR.

2018-05-19 22:28 UTC, erikannunez commented on src/main/java/edu/uade/apd/tpo/controller/SistemaDeposito.java
> +    	stock.agregarMovimientoIngreso(MotivoIngreso.COMPRA, cantidad);
Luego de almacenar falta persistirlo.

2018-05-19 22:28 UTC, erikannunez commented on src/main/java/edu/uade/apd/tpo/controller/SistemaDeposito.java
> +    public List<ItemLote> obtenerLotesPorArticulo(Long articuloId, int cantidad) {
eliminar este método ya que no tiene la funcionalidad adecuada. Luego mergear la branch con develop, y posteriormente generar un nuevo pr.

2018-05-19 22:28 UTC, erikannunez commented on src/main/java/edu/uade/apd/tpo/model/Posicion.java
> +    	this.guardar();
Eliminar el this.guardar(). Llamar a guardar() desde afuera, en el SistemaDeposito.

2018-05-19 22:28 UTC, erikannunez commented on src/main/java/edu/uade/apd/tpo/model/Posicion.java
> +    	this.guardar();
Eliminar el this.guardar(). Llamar a guardar() desde afuera, en el SistemaDeposito.

2018-05-19 22:28 UTC, erikannunez commented on src/main/java/edu/uade/apd/tpo/controller/SistemaDeposito.java
> +    	posicion.liberar(cantidad);
Luego de liberar, llamar al método guardar para persistir el objeto.

2018-05-20 16:15 UTC, erikannunez requested changes

2018-05-20 16:15 UTC, erikannunez commented on src/main/java/edu/uade/apd/tpo/controller/SistemaDeposito.java
> -    public static SistemaDeposito getInstance() {
El getInstance no debe eliminarse

2018-05-20 16:15 UTC, erikannunez commented on src/main/java/edu/uade/apd/tpo/controller/SistemaDeposito.java
> +    	posicionDao.save(posicion);
Hay que llamar a posicion.guardar() y dentro de posicion.guardar() se llama a posicionDao.getInstance().save(this).-
Tomar de referencia el SistemaFacturacion y la Factura.-

2018-05-20 16:15 UTC, erikannunez commented on src/main/java/edu/uade/apd/tpo/dao/impl/PosicionDao.java
> +                	   "where f.estado = :DISPONIBLE";
En este caso creo que debería ser where f.estado = 'DISPONIBLE'... Ya que los dos puntos son para pasar parámetros. @mundobaton

2018-05-20 16:15 UTC, erikannunez commented on src/main/java/edu/uade/apd/tpo/controller/SistemaDeposito.java
> +	    	    	posicionDao.save(posicion);
cambiar por posicion.guardar()

2018-05-20 16:15 UTC, erikannunez commented on src/main/java/edu/uade/apd/tpo/controller/SistemaDeposito.java
> +    	stock.agregarMovimientoIngreso(MotivoIngreso.COMPRA, cantidad);
Revisar. En qué momento se persiste el cambio de stock del artículo?
@mundobaton

2018-05-20 20:55 UTC, mundobaton commented on src/main/java/edu/uade/apd/tpo/controller/SistemaDeposito.java
> +    	stock.agregarMovimientoIngreso(MotivoIngreso.COMPRA, cantidad);
falta persistir el articulo

2018-05-21 12:55 UTC, merged